### ISSUE TITLE
Add license (e.g., MIT or BSD)

### ISSUE THREAD

**Issue by pdhahn** [arntanguy/gram_savitzky_golay#1]
Please add a license file for this code. Use MIT or BSD license so this code can be used without issue in any kind of application, including commercial.

**Comment by arntanguy** [comment]
I've licenced it under LGPL, feel free to use it, and improve it as you like.

**Comment by pdhahn** [comment]
Oh I wish I could but now it's under LGPL, not a commercial-friendly MIT or BSD (or ZLIB, Apache, etc.) license. Any 3rd party package with "(L)GPL" terms is a non-starter for me in commercial product development. Thanks anyway! :-)

**Comment by arntanguy** [comment]
> The LGPL is similar to the GPL, but is more designed for software libraries where you want to allow non-GPL applications to link to your library and utilise it. If you modify the software, you still have to give back the source code, but you are allowed to link it with proprietary stuff without giving the source code to all of that back.

What's wrong with that?

**Comment by arntanguy** [comment]
This package has been relicenced as BSD-2 now.
