### ISSUE TITLE
I can't install the libgram-savitzy-golay-dev.Is it still available?

### ISSUE THREAD

**Issue by qxang1001** [arntanguy/gram_savitzky_golay#12]
![微信图片_20240623215208](https://github.com/arntanguy/gram_savitzky_golay/assets/105415412/f4855bd6-e520-4426-a59f-fcec71aa7424)
My ubuntu version is 20.04

**Comment by arntanguy** [comment]
Sorry about that, indeed the bintray repository no longer exists and I haven't taken the time to set up a new one.
In the meanwhile you can easily build the library from souce.
